apiVersion: apps/v1
kind: Deployment
metadata:
  name: facekey-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: facekey-frontend
  template:
    metadata:
      labels:
        app: facekey-frontend
    spec:
      containers:
      - name: facekey-frontend
        image: your-dockerhub-user/facekey-frontend:latest
        ports:
        - containerPort: 80

